### ISSUE TITLE
Error: no commands defined in the "ide-helper" namespace.

### ISSUE THREAD

**Issue by Y4k3d0** [Flynsarmy/wn-idehelper-plugin#2]
Similar issue than the October version of this plugin.

After following the installation steps, I try running `php artisan ide-helper:generate`, then I get this error :

```
There are no commands defined in the "ide-helper" namespace.
```

**Comment by Flynsarmy** [comment]
I can't replicate this issue.

**Comment by shaxzodbe** [comment]
In my case you install 
**composer require barryvdh/laravel-debugbar --dev**  
but, you need to install with 
**composer uninstall barryvdh/laravel-ide-helper**
